export type Phone = {
  id: string;
  brand: string;
  model: string;
  storage: string;
  network: string;
  monthlyPrice: number;
  upfrontPrice: number;
  data: string;
  contractDuration: string;
  badge: string;
  image: string;
  category: 'phone' | 'refurbished';
  condition?: string;
  battery?: string;
  warranty?: string;
  price?: number;
  is5G?: boolean;
  isBudget?: boolean;
};

export type SimPlan = {
  id: string;
  data: string;
  monthlyPrice: number;
  network: string;
  is5G: boolean;
  isUnlimited: boolean;
  badge?: string;
  contractDuration?: string;
};

export type DevicePlan = {
  id: string;
  brand: string;
  model: string;
  storage: string;
  image: string;
  network: string;
  deviceMonthly: number;
  simMonthly: number;
  totalMonthly: number;
  upfront: number;
  data: string;
  contractDuration: string;
  badge: string;
  is5G: boolean;
};

export type Brand = {
  name: string;
  image: string;
};

export type Network = {
  name: string;
  color: string;
  tagline: string;
};

export type Review = {
  name: string;
  rating: number;
  text: string;
  location: string;
};

export type Faq = {
  question: string;
  answer: string;
};

export const phones: Phone[] = [
  {
    id: 'iphone-17',
    brand: 'Apple',
    model: 'iPhone 17',
    storage: '256GB',
    network: 'EE',
    monthlyPrice: 49,
    upfrontPrice: 99,
    data: 'Unlimited Data',
    contractDuration: '24 months',
    badge: 'NEW',
    image: 'https://images.pexels.com/photos/37467615/pexels-photo-37467615.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    category: 'phone',
    is5G: true,
  },
  {
    id: 'iphone-16',
    brand: 'Apple',
    model: 'iPhone 16',
    storage: '128GB',
    network: 'Vodafone',
    monthlyPrice: 39,
    upfrontPrice: 79,
    data: '400GB 5G',
    contractDuration: '24 months',
    badge: 'POPULAR',
    image: 'https://images.pexels.com/photos/30639091/pexels-photo-30639091.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    category: 'phone',
    is5G: true,
  },
  {
    id: 'galaxy-s26',
    brand: 'Samsung',
    model: 'Galaxy S26',
    storage: '256GB',
    network: 'O2',
    monthlyPrice: 44,
    upfrontPrice: 89,
    data: 'Unlimited Data',
    contractDuration: '24 months',
    badge: 'BEST VALUE',
    image: 'https://images.pexels.com/photos/30466731/pexels-photo-30466731.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    category: 'phone',
    is5G: true,
  },
  {
    id: 'galaxy-s25',
    brand: 'Samsung',
    model: 'Galaxy S25',
    storage: '128GB',
    network: 'Three',
    monthlyPrice: 35,
    upfrontPrice: 59,
    data: '200GB 5G',
    contractDuration: '24 months',
    badge: '5G',
    image: 'https://images.pexels.com/photos/28687649/pexels-photo-28687649.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    category: 'phone',
    is5G: true,
  },
  {
    id: 'pixel-10',
    brand: 'Google',
    model: 'Pixel 10',
    storage: '128GB',
    network: 'iD Mobile',
    monthlyPrice: 32,
    upfrontPrice: 49,
    data: '100GB 5G',
    contractDuration: '24 months',
    badge: 'LIMITED OFFER',
    image: 'https://images.pexels.com/photos/32218867/pexels-photo-32218867.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    category: 'phone',
    is5G: true,
    isBudget: true,
  },
  {
    id: 'pixel-10-pro',
    brand: 'Google',
    model: 'Pixel 10 Pro',
    storage: '256GB',
    network: 'giffgaff',
    monthlyPrice: 42,
    upfrontPrice: 69,
    data: 'Unlimited Data',
    contractDuration: '24 months',
    badge: 'POPULAR',
    image: 'https://images.pexels.com/photos/11934173/pexels-photo-11934173.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    category: 'phone',
    is5G: true,
  },
  {
    id: 'galaxy-a56',
    brand: 'Samsung',
    model: 'Galaxy A56',
    storage: '128GB',
    network: 'SMARTY',
    monthlyPrice: 19,
    upfrontPrice: 0,
    data: '50GB 5G',
    contractDuration: '24 months',
    badge: 'BUDGET',
    image: 'https://images.pexels.com/photos/16149966/pexels-photo-16149966.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    category: 'phone',
    is5G: true,
    isBudget: true,
  },
  {
    id: 'iphone-16-plus',
    brand: 'Apple',
    model: 'iPhone 16 Plus',
    storage: '256GB',
    network: 'Sky Mobile',
    monthlyPrice: 45,
    upfrontPrice: 99,
    data: 'Unlimited Data',
    contractDuration: '24 months',
    badge: '5G',
    image: 'https://images.pexels.com/photos/8490071/pexels-photo-8490071.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    category: 'phone',
    is5G: true,
  },
  {
    id: 'oneplus-13',
    brand: 'OnePlus',
    model: 'OnePlus 13',
    storage: '256GB',
    network: 'Three',
    monthlyPrice: 38,
    upfrontPrice: 49,
    data: '200GB 5G',
    contractDuration: '24 months',
    badge: 'BEST VALUE',
    image: 'https://images.pexels.com/photos/16168364/pexels-photo-16168364.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    category: 'phone',
    is5G: true,
  },
  {
    id: 'xiaomi-15',
    brand: 'Xiaomi',
    model: 'Xiaomi 15',
    storage: '256GB',
    network: 'Lebara',
    monthlyPrice: 29,
    upfrontPrice: 0,
    data: '100GB 5G',
    contractDuration: '24 months',
    badge: 'BUDGET',
    image: 'https://images.pexels.com/photos/28077969/pexels-photo-28077969.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    category: 'phone',
    is5G: true,
    isBudget: true,
  },
  {
    id: 'honor-200',
    brand: 'Honor',
    model: 'Honor 200',
    storage: '128GB',
    network: 'Tesco Mobile',
    monthlyPrice: 24,
    upfrontPrice: 0,
    data: '75GB 5G',
    contractDuration: '24 months',
    badge: 'LIMITED OFFER',
    image: 'https://images.pexels.com/photos/16144578/pexels-photo-16144578.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    category: 'phone',
    is5G: true,
    isBudget: true,
  },
  {
    id: 'motorola-edge',
    brand: 'Motorola',
    model: 'Edge 50',
    storage: '256GB',
    network: 'Talkmobile',
    monthlyPrice: 22,
    upfrontPrice: 0,
    data: '60GB 5G',
    contractDuration: '24 months',
    badge: 'BUDGET',
    image: 'https://images.pexels.com/photos/9995703/pexels-photo-9995703.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    category: 'phone',
    is5G: true,
    isBudget: true,
  },
  {
    id: 'iphone-17-pro',
    brand: 'Apple',
    model: 'iPhone 17 Pro',
    storage: '512GB',
    network: 'EE',
    monthlyPrice: 59,
    upfrontPrice: 149,
    data: 'Unlimited Data',
    contractDuration: '24 months',
    badge: 'NEW',
    image: 'https://images.pexels.com/photos/37889435/pexels-photo-37889435.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    category: 'phone',
    is5G: true,
  },
  {
    id: 'galaxy-s26-ultra',
    brand: 'Samsung',
    model: 'Galaxy S26 Ultra',
    storage: '512GB',
    network: 'Vodafone',
    monthlyPrice: 54,
    upfrontPrice: 129,
    data: 'Unlimited Data',
    contractDuration: '24 months',
    badge: 'BEST VALUE',
    image: 'https://images.pexels.com/photos/30466739/pexels-photo-30466739.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    category: 'phone',
    is5G: true,
  },
  {
    id: 'galaxy-z-fold',
    brand: 'Samsung',
    model: 'Galaxy Z Fold 7',
    storage: '256GB',
    network: 'O2',
    monthlyPrice: 62,
    upfrontPrice: 199,
    data: 'Unlimited Data',
    contractDuration: '24 months',
    badge: 'NEW',
    image: 'https://images.pexels.com/photos/19022731/pexels-photo-19022731.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    category: 'phone',
    is5G: true,
  },
  {
    id: 'pixel-10-pro-xl',
    brand: 'Google',
    model: 'Pixel 10 Pro XL',
    storage: '512GB',
    network: 'Three',
    monthlyPrice: 48,
    upfrontPrice: 99,
    data: 'Unlimited Data',
    contractDuration: '24 months',
    badge: 'POPULAR',
    image: 'https://images.pexels.com/photos/17577863/pexels-photo-17577863.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    category: 'phone',
    is5G: true,
  },
  {
    id: 'oneplus-13r',
    brand: 'OnePlus',
    model: 'OnePlus 13R',
    storage: '128GB',
    network: 'iD Mobile',
    monthlyPrice: 26,
    upfrontPrice: 0,
    data: '100GB 5G',
    contractDuration: '24 months',
    badge: 'BUDGET',
    image: 'https://images.pexels.com/photos/19281807/pexels-photo-19281807.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    category: 'phone',
    is5G: true,
    isBudget: true,
  },
  {
    id: 'xiaomi-redmi-note',
    brand: 'Xiaomi',
    model: 'Redmi Note 14',
    storage: '128GB',
    network: 'SMARTY',
    monthlyPrice: 16,
    upfrontPrice: 0,
    data: '40GB 5G',
    contractDuration: '24 months',
    badge: 'BUDGET',
    image: 'https://images.pexels.com/photos/20074761/pexels-photo-20074761.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    category: 'phone',
    is5G: true,
    isBudget: true,
  },
  {
    id: 'honor-magic-7',
    brand: 'Honor',
    model: 'Magic 7 Pro',
    storage: '256GB',
    network: 'Tesco Mobile',
    monthlyPrice: 34,
    upfrontPrice: 49,
    data: '150GB 5G',
    contractDuration: '24 months',
    badge: 'LIMITED OFFER',
    image: 'https://images.pexels.com/photos/20074768/pexels-photo-20074768.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    category: 'phone',
    is5G: true,
  },
  {
    id: 'motorola-g85',
    brand: 'Motorola',
    model: 'Moto G85',
    storage: '128GB',
    network: 'Talkmobile',
    monthlyPrice: 14,
    upfrontPrice: 0,
    data: '30GB 5G',
    contractDuration: '24 months',
    badge: 'BUDGET',
    image: 'https://images.pexels.com/photos/11934173/pexels-photo-11934173.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    category: 'phone',
    is5G: true,
    isBudget: true,
  },
  {
    id: 'iphone-16-pro',
    brand: 'Apple',
    model: 'iPhone 16 Pro',
    storage: '256GB',
    network: 'O2',
    monthlyPrice: 52,
    upfrontPrice: 129,
    data: 'Unlimited Data',
    contractDuration: '24 months',
    badge: 'POPULAR',
    image: 'https://images.pexels.com/photos/21263369/pexels-photo-21263369.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    category: 'phone',
    is5G: true,
  },
  {
    id: 'galaxy-a36',
    brand: 'Samsung',
    model: 'Galaxy A36',
    storage: '128GB',
    network: 'Sky Mobile',
    monthlyPrice: 18,
    upfrontPrice: 0,
    data: '45GB 5G',
    contractDuration: '24 months',
    badge: 'BUDGET',
    image: 'https://images.pexels.com/photos/16149966/pexels-photo-16149966.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    category: 'phone',
    is5G: true,
    isBudget: true,
  },
  {
    id: 'pixel-9a',
    brand: 'Google',
    model: 'Pixel 9a',
    storage: '128GB',
    network: 'giffgaff',
    monthlyPrice: 21,
    upfrontPrice: 0,
    data: '60GB 5G',
    contractDuration: '24 months',
    badge: 'BUDGET',
    image: 'https://images.pexels.com/photos/16168366/pexels-photo-16168366.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    category: 'phone',
    is5G: true,
    isBudget: true,
  },
  {
    id: 'oneplus-nord-5',
    brand: 'OnePlus',
    model: 'OnePlus Nord 5',
    storage: '128GB',
    network: 'VOXI',
    monthlyPrice: 20,
    upfrontPrice: 0,
    data: '50GB 5G',
    contractDuration: '24 months',
    badge: 'LIMITED OFFER',
    image: 'https://images.pexels.com/photos/16168364/pexels-photo-16168364.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    category: 'phone',
    is5G: true,
    isBudget: true,
  },
];

export const refurbishedPhones: Phone[] = [
  {
    id: 'refurb-iphone-15',
    brand: 'Apple',
    model: 'iPhone 15',
    storage: '128GB',
    network: 'Refurbished',
    monthlyPrice: 0,
    upfrontPrice: 0,
    data: '',
    contractDuration: '',
    badge: 'EXCELLENT',
    image: 'https://images.pexels.com/photos/6031544/pexels-photo-6031544.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    category: 'refurbished',
    condition: 'Excellent Condition',
    battery: 'Battery 90%+',
    warranty: '12 Month Warranty',
    price: 399,
  },
  {
    id: 'refurb-galaxy-s24',
    brand: 'Samsung',
    model: 'Galaxy S24',
    storage: '256GB',
    network: 'Refurbished',
    monthlyPrice: 0,
    upfrontPrice: 0,
    data: '',
    contractDuration: '',
    badge: 'VERY GOOD',
    image: 'https://images.pexels.com/photos/13780425/pexels-photo-13780425.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    category: 'refurbished',
    condition: 'Very Good Condition',
    battery: 'Battery 85%+',
    warranty: '12 Month Warranty',
    price: 329,
  },
  {
    id: 'refurb-pixel-9',
    brand: 'Google',
    model: 'Pixel 9',
    storage: '128GB',
    network: 'Refurbished',
    monthlyPrice: 0,
    upfrontPrice: 0,
    data: '',
    contractDuration: '',
    badge: 'EXCELLENT',
    image: 'https://images.pexels.com/photos/3999536/pexels-photo-3999536.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    category: 'refurbished',
    condition: 'Excellent Condition',
    battery: 'Battery 92%+',
    warranty: '12 Month Warranty',
    price: 299,
  },
  {
    id: 'refurb-iphone-14',
    brand: 'Apple',
    model: 'iPhone 14',
    storage: '128GB',
    network: 'Refurbished',
    monthlyPrice: 0,
    upfrontPrice: 0,
    data: '',
    contractDuration: '',
    badge: 'GOOD',
    image: 'https://images.pexels.com/photos/8381365/pexels-photo-8381365.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    category: 'refurbished',
    condition: 'Good Condition',
    battery: 'Battery 80%+',
    warranty: '6 Month Warranty',
    price: 249,
  },
];

export const simPlans: SimPlan[] = [
  {
    id: 'sim-5gb',
    data: '5GB',
    monthlyPrice: 5,
    network: 'SMARTY',
    is5G: false,
    isUnlimited: false,
    badge: 'BUDGET',
    contractDuration: '30-day',
  },
  {
    id: 'sim-15gb',
    data: '15GB',
    monthlyPrice: 8,
    network: 'VOXI',
    is5G: false,
    isUnlimited: false,
    badge: 'BUDGET',
    contractDuration: '30-day',
  },
  {
    id: 'sim-20gb',
    data: '20GB 5G',
    monthlyPrice: 10,
    network: 'SMARTY',
    is5G: true,
    isUnlimited: false,
    badge: 'POPULAR',
    contractDuration: '30-day',
  },
  {
    id: 'sim-30gb',
    data: '30GB 5G',
    monthlyPrice: 11,
    network: 'Talkmobile',
    is5G: true,
    isUnlimited: false,
    contractDuration: '30-day',
  },
  {
    id: 'sim-50gb',
    data: '50GB 5G',
    monthlyPrice: 12,
    network: 'giffgaff',
    is5G: true,
    isUnlimited: false,
    contractDuration: '30-day',
  },
  {
    id: 'sim-75gb',
    data: '75GB 5G',
    monthlyPrice: 14,
    network: 'Tesco Mobile',
    is5G: true,
    isUnlimited: false,
    contractDuration: '30-day',
  },
  {
    id: 'sim-100gb',
    data: '100GB 5G',
    monthlyPrice: 15,
    network: 'iD Mobile',
    is5G: true,
    isUnlimited: false,
    badge: 'POPULAR',
    contractDuration: '30-day',
  },
  {
    id: 'sim-150gb',
    data: '150GB 5G',
    monthlyPrice: 18,
    network: 'Lebara',
    is5G: true,
    isUnlimited: false,
    contractDuration: '12-month',
  },
  {
    id: 'sim-200gb',
    data: '200GB 5G',
    monthlyPrice: 20,
    network: 'Three',
    is5G: true,
    isUnlimited: false,
    badge: 'BEST VALUE',
    contractDuration: '12-month',
  },
  {
    id: 'sim-300gb',
    data: '300GB 5G',
    monthlyPrice: 22,
    network: 'Sky Mobile',
    is5G: true,
    isUnlimited: false,
    contractDuration: '12-month',
  },
  {
    id: 'sim-unlimited',
    data: 'Unlimited Data',
    monthlyPrice: 25,
    network: 'EE',
    is5G: true,
    isUnlimited: true,
    badge: 'UNLIMITED',
    contractDuration: '12-month',
  },
  {
    id: 'sim-unlimited-plus',
    data: 'Unlimited Data + 5G',
    monthlyPrice: 30,
    network: 'Vodafone',
    is5G: true,
    isUnlimited: true,
    badge: 'UNLIMITED',
    contractDuration: '12-month',
  },
  {
    id: 'sim-unlimited-o2',
    data: 'Unlimited Data',
    monthlyPrice: 27,
    network: 'O2',
    is5G: true,
    isUnlimited: true,
    badge: 'UNLIMITED',
    contractDuration: '12-month',
  },
  {
    id: 'sim-unlimited-three',
    data: 'Unlimited Data + 5G',
    monthlyPrice: 24,
    network: 'Three',
    is5G: true,
    isUnlimited: true,
    badge: 'BEST VALUE',
    contractDuration: '12-month',
  },
];

export const devicePlans: DevicePlan[] = [
  {
    id: 'dp-iphone-17-ee',
    brand: 'Apple',
    model: 'iPhone 17',
    storage: '256GB',
    image: 'https://images.pexels.com/photos/37467615/pexels-photo-37467615.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    network: 'EE',
    deviceMonthly: 35,
    simMonthly: 14,
    totalMonthly: 49,
    upfront: 99,
    data: 'Unlimited Data',
    contractDuration: '36 months',
    badge: 'NEW',
    is5G: true,
  },
  {
    id: 'dp-galaxy-s26-o2',
    brand: 'Samsung',
    model: 'Galaxy S26',
    storage: '256GB',
    image: 'https://images.pexels.com/photos/30466731/pexels-photo-30466731.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    network: 'O2',
    deviceMonthly: 30,
    simMonthly: 14,
    totalMonthly: 44,
    upfront: 89,
    data: 'Unlimited Data',
    contractDuration: '36 months',
    badge: 'BEST VALUE',
    is5G: true,
  },
  {
    id: 'dp-pixel-10-id',
    brand: 'Google',
    model: 'Pixel 10',
    storage: '128GB',
    image: 'https://images.pexels.com/photos/32218867/pexels-photo-32218867.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    network: 'iD Mobile',
    deviceMonthly: 20,
    simMonthly: 12,
    totalMonthly: 32,
    upfront: 49,
    data: '100GB 5G',
    contractDuration: '36 months',
    badge: 'LIMITED OFFER',
    is5G: true,
  },
  {
    id: 'dp-iphone-16-vodafone',
    brand: 'Apple',
    model: 'iPhone 16',
    storage: '128GB',
    image: 'https://images.pexels.com/photos/30639091/pexels-photo-30639091.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    network: 'Vodafone',
    deviceMonthly: 25,
    simMonthly: 14,
    totalMonthly: 39,
    upfront: 79,
    data: '400GB 5G',
    contractDuration: '36 months',
    badge: 'POPULAR',
    is5G: true,
  },
  {
    id: 'dp-galaxy-s25-three',
    brand: 'Samsung',
    model: 'Galaxy S25',
    storage: '128GB',
    image: 'https://images.pexels.com/photos/28687649/pexels-photo-28687649.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    network: 'Three',
    deviceMonthly: 22,
    simMonthly: 13,
    totalMonthly: 35,
    upfront: 59,
    data: '200GB 5G',
    contractDuration: '36 months',
    badge: '5G',
    is5G: true,
  },
  {
    id: 'dp-oneplus-13-three',
    brand: 'OnePlus',
    model: 'OnePlus 13',
    storage: '256GB',
    image: 'https://images.pexels.com/photos/16168364/pexels-photo-16168364.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    network: 'Three',
    deviceMonthly: 24,
    simMonthly: 14,
    totalMonthly: 38,
    upfront: 49,
    data: '200GB 5G',
    contractDuration: '36 months',
    badge: 'BEST VALUE',
    is5G: true,
  },
  {
    id: 'dp-xiaomi-15-lebara',
    brand: 'Xiaomi',
    model: 'Xiaomi 15',
    storage: '256GB',
    image: 'https://images.pexels.com/photos/28077969/pexels-photo-28077969.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    network: 'Lebara',
    deviceMonthly: 16,
    simMonthly: 13,
    totalMonthly: 29,
    upfront: 0,
    data: '100GB 5G',
    contractDuration: '36 months',
    badge: 'BUDGET',
    is5G: true,
  },
  {
    id: 'dp-honor-200-tesco',
    brand: 'Honor',
    model: 'Honor 200',
    storage: '128GB',
    image: 'https://images.pexels.com/photos/16144578/pexels-photo-16144578.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    network: 'Tesco Mobile',
    deviceMonthly: 12,
    simMonthly: 12,
    totalMonthly: 24,
    upfront: 0,
    data: '75GB 5G',
    contractDuration: '36 months',
    badge: 'LIMITED OFFER',
    is5G: true,
  },
  {
    id: 'dp-motorola-edge-talkmobile',
    brand: 'Motorola',
    model: 'Edge 50',
    storage: '256GB',
    image: 'https://images.pexels.com/photos/9995703/pexels-photo-9995703.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    network: 'Talkmobile',
    deviceMonthly: 10,
    simMonthly: 12,
    totalMonthly: 22,
    upfront: 0,
    data: '60GB 5G',
    contractDuration: '36 months',
    badge: 'BUDGET',
    is5G: true,
  },
  {
    id: 'dp-iphone-17-pro-ee',
    brand: 'Apple',
    model: 'iPhone 17 Pro',
    storage: '512GB',
    image: 'https://images.pexels.com/photos/37889435/pexels-photo-37889435.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    network: 'EE',
    deviceMonthly: 42,
    simMonthly: 17,
    totalMonthly: 59,
    upfront: 149,
    data: 'Unlimited Data',
    contractDuration: '36 months',
    badge: 'NEW',
    is5G: true,
  },
  {
    id: 'dp-galaxy-z-fold-o2',
    brand: 'Samsung',
    model: 'Galaxy Z Fold 7',
    storage: '256GB',
    image: 'https://images.pexels.com/photos/19022731/pexels-photo-19022731.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    network: 'O2',
    deviceMonthly: 45,
    simMonthly: 17,
    totalMonthly: 62,
    upfront: 199,
    data: 'Unlimited Data',
    contractDuration: '36 months',
    badge: 'NEW',
    is5G: true,
  },
  {
    id: 'dp-pixel-10-pro-giffgaff',
    brand: 'Google',
    model: 'Pixel 10 Pro',
    storage: '256GB',
    image: 'https://images.pexels.com/photos/11934173/pexels-photo-11934173.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    network: 'giffgaff',
    deviceMonthly: 28,
    simMonthly: 14,
    totalMonthly: 42,
    upfront: 69,
    data: 'Unlimited Data',
    contractDuration: '36 months',
    badge: 'POPULAR',
    is5G: true,
  },
];

export const brands: Brand[] = [
  { name: 'Apple', image: 'https://images.pexels.com/photos/30639091/pexels-photo-30639091.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
  { name: 'Samsung', image: 'https://images.pexels.com/photos/30466731/pexels-photo-30466731.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
  { name: 'Google', image: 'https://images.pexels.com/photos/32218867/pexels-photo-32218867.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
  { name: 'Motorola', image: 'https://images.pexels.com/photos/9995703/pexels-photo-9995703.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
  { name: 'Honor', image: 'https://images.pexels.com/photos/16144578/pexels-photo-16144578.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
  { name: 'OnePlus', image: 'https://images.pexels.com/photos/16168364/pexels-photo-16168364.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
  { name: 'Xiaomi', image: 'https://images.pexels.com/photos/28077969/pexels-photo-28077969.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
];

export const networks: Network[] = [
  { name: 'EE', color: '#00B8F1', tagline: 'Superfast 5G' },
  { name: 'O2', color: '#0066CC', tagline: 'More for you' },
  { name: 'Vodafone', color: '#E60000', tagline: 'Together we can' },
  { name: 'Three', color: '#000000', tagline: 'Connect more' },
  { name: 'iD Mobile', color: '#8A2BE2', tagline: 'Flexible plans' },
  { name: 'giffgaff', color: '#D4AC0D', tagline: 'The mobile network' },
  { name: 'Sky Mobile', color: '#FF8C00', tagline: 'Roll your data' },
  { name: 'Tesco Mobile', color: '#00539F', tagline: 'Little helps' },
  { name: 'SMARTY', color: '#FF00FF', tagline: 'No-frills SIM' },
  { name: 'VOXI', color: '#E91E63', tagline: 'Endless social' },
  { name: 'Talkmobile', color: '#4A90D9', tagline: 'Simple value' },
  { name: 'Lebara', color: '#1E8449', tagline: 'Global calls' },
];

export const reviews: Review[] = [
  { name: 'Sarah M.', rating: 5, text: 'Really easy to compare different phone deals. Found a great SIM plan in minutes.', location: 'Manchester' },
  { name: 'James T.', rating: 5, text: 'Saved £15 a month on my phone contract by comparing networks here. Brilliant.', location: 'Birmingham' },
  { name: 'Priya K.', rating: 4, text: 'Loved the refurbished section. Got a like-new iPhone for half the price.', location: 'London' },
  { name: 'David W.', rating: 5, text: 'The trade-in calculator gave me a fair estimate. Smooth process overall.', location: 'Leeds' },
];

export const faqs: Faq[] = [
  { question: 'What is SIM Only?', answer: 'A SIM Only plan gives you a SIM card with data, minutes and texts without a new phone. It is usually cheaper and comes on a 30-day or 12-month rolling contract.' },
  { question: 'What is SIM Free?', answer: 'A SIM Free phone is a handset bought without a SIM card or contract. You own the phone outright and can use any SIM card from any network.' },
  { question: 'What is a phone contract?', answer: 'A phone contract bundles a smartphone with a monthly plan of data, minutes and texts. You typically pay an upfront cost and a fixed monthly fee over 24 months.' },
  { question: 'What is a device installment plan?', answer: 'A device installment plan lets you spread the cost of a phone over 36 months, combined with a SIM plan. You pay a monthly device fee plus a monthly SIM fee, often with lower upfront costs.' },
  { question: 'What is 5G?', answer: '5G is the latest generation of mobile network technology, offering faster download speeds, lower latency and better performance in busy areas compared to 4G.' },
  { question: 'What is a refurbished phone?', answer: 'A refurbished phone is a pre-owned device that has been tested, repaired and restored to a like-new or very good condition. They come with a warranty and are significantly cheaper than new.' },
  { question: 'Can I trade in my old phone?', answer: 'Yes! Use our trade-in estimator to get an indicative value for your old device. You can then put that value towards your next phone or SIM plan.' },
  { question: 'Which UK networks are available?', answer: 'We feature deals from major UK networks including EE, O2, Vodafone, Three, iD Mobile, giffgaff, Sky Mobile, Tesco Mobile, SMARTY, VOXI, Talkmobile and Lebara.' },
  { question: 'Are the prices on this website live?', answer: 'Prices shown on this demo website are illustrative and are not live network pricing. They are for demonstration purposes only.' },
];

export const dealCategories = [
  { id: 'all', label: 'All Deals' },
  { id: 'phone', label: 'Phone Deals' },
  { id: 'sim', label: 'SIM Deals' },
  { id: 'device', label: 'Device Plans' },
  { id: '5g', label: '5G Deals' },
  { id: 'refurbished', label: 'Refurbished' },
  { id: 'budget', label: 'Budget Deals' },
];

export const simFilters = [
  { id: 'all', label: 'All' },
  { id: '5g', label: '5G' },
  { id: 'unlimited', label: 'Unlimited' },
  { id: 'under15', label: 'Under £15' },
  { id: '12month', label: '12-Month' },
];

export const devicePlanFilters = [
  { id: 'all', label: 'All Plans' },
  { id: '5g', label: '5G' },
  { id: 'unlimited', label: 'Unlimited Data' },
  { id: 'noupfront', label: 'No Upfront' },
  { id: 'under35', label: 'Under £35/mo' },
];
